on:
  push:
    branches: ["dev"]
env:
  IMAGE_VERSION: ${{ vars.IMAGE_TAG }}
name: Publishing app
jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # - name: Building App
      #   run: docker build -f Dockerfile_app -t krystian8207/sales_app_build:$IMAGE_VERSION .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # - name: Publishing Image
      #   run: docker push krystian8207/sales_app_build:$IMAGE_VERSION
      - name: Running App on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker run -p 8888:8888 krystian8207/sales_app_build:1.1
